version: "3.8"

services:
  test:
    depends_on:
      mysql:
        condition: service_healthy
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  mysql:
    container_name: mysql
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - .dev/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 0s
