services:
  poc:
    depends_on:
      mysql:
        condition: service_healthy
    container_name: poc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  mysql:
    container_name: mysql
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ".dev/tables.sql:/docker-entrypoint-initdb.d/tables.sql"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 0s

  localstack:
    container_name: localstack
    image: localstack/localstack:3.4.0
    network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".dev/localstack.sh:/etc/localstack/init/ready.d/localstack.sh"
